### ISSUE TITLE
Purchase Timestamp Data Types

### ISSUE THREAD

**Issue by micahalcorn** [OriginProtocol/origin-bridge#102]
Purchase timestamps are currently being returned by the API as [ISO strings](https://en.wikipedia.org/wiki/ISO_8601). They should be returned as seconds since the epoch because they are integers on the blockchain and [Origin.js expects to return datetimes](http://docs.originprotocol.com/#purchase-get). It would probably also be preferable for the field names to match, such as `created` instead of `created_at`.

![screen shot 2018-07-05 at 12 51 20 pm](https://user-images.githubusercontent.com/273937/42345362-e8b93bbe-8053-11e8-9792-4c75f3737e24.png)

**Comment by tomlinton** [comment]
Closed as bridge no longer does indexing.
