### ISSUE TITLE
Support indexing Fractional Listings / only index Unit Listings

### ISSUE THREAD

**Issue by ambertch** [OriginProtocol/origin-bridge#105]
Currently, with the refactor to Unit and Fractional Listings, the two subclasses have different data fields.

The indexer code has been modified to retrieve listing data for Unit Listings https://github.com/OriginProtocol/origin-bridge/blob/develop/logic/indexer_service.py#L153 , however NewListing events are emitted for all listings, so the celery worker will invoke the indexer with a NewListing event that is for a Fractional Listing.

**Comment by ambertch** [comment]
(this is strangely both a bug and a feature)

**Comment by tomlinton** [comment]
Closed cause bridge no longer does indexing.
