### ISSUE TITLE
Implement an internal API for indexing Listings and Purchases into the DB

### ISSUE THREAD

**Issue by franckc** [OriginProtocol/origin-bridge#123]
As part of the design for indexing (see [doc](https://docs.google.com/document/d/1v6N--Ncyea12irHysE8QafmjnCRy01YKm7Fqtxq2rNc/edit#)), the EventListener will call a bridge server internal API to index Listings and Purchases in the Database.

**Comment by tomlinton** [comment]
Closing this as `origin-bridge` no longer handles indexing.
