### ISSUE TITLE
Delete event listener and contract code

### ISSUE THREAD

**Issue by franckc** [OriginProtocol/origin-bridge#133]
Now that we are moving towards a Node.js EventListener implementation, we need to delete the old bridge server code and contracts JSON that was used for listening to events.
It is going to be replaced by the following:
 - Search and DB indexers will be built-in the EventListener
 - Mobile notification will be a bridge server webhook called by the EventListener.

Also we should delete the origin-bridge-celery container since it becomes irrelevant.

**Comment by tomlinton** [comment]
@franckc it looks like this was covered in #134? OK to close?

**Comment by franckc** [comment]
Yes, this was done. Closing...
