### ISSUE TITLE
Airbnb attestations don't work with international domains

### ISSUE THREAD

**Issue by joshfraser** [OriginProtocol/origin-bridge#136]
The current Airbnb attestation service expects the Airbnb domain to be airbnb.com but regional domains like airbnb.co.uk are just as valid.

**Comment by franckc** [comment]
Ah good catch. @joshfraser is that a p0 ? or can we fix shortly after V1 ?

**Comment by franckc** [comment]
Sounds good. Let's prioritize it for after V1 then...

**Comment by tomlinton** [comment]
Does this impact the functionality of the attestation though? My understanding was that the international version of the Airbnb domain will serve up the same page but with different localisation settings like language which shouldn't prevent our attestation from working.

**Comment by sparrowDom** [comment]
@tomlinton yeah you are right. The part that needs some adjustments is probably just the form validation, that will not let any domains other than airbnb.com through.

**Comment by tomlinton** [comment]
Fixed in [#748](https://github.com/OriginProtocol/origin/pull/748).
