### ISSUE TITLE
Return Twitter and Facebook account IDs with attestation responses

### ISSUE THREAD

**Issue by tomlinton** [OriginProtocol/origin-bridge#140]
On OAuth success the response should include the account ID for Twitter and Facebook to allow `origin-dapp` to store them in IPFS via `origin-js`.

**Comment by micahalcorn** [comment]
Please confirm the same for Airbnb, if possible.

**Comment by sparrowDom** [comment]
Yup the same goes for Airbnb

**Comment by sparrowDom** [comment]
We have decoded not to store Facebook identification into attestation for privacy reasons. For Twitter and Aribnb this is solved via: https://github.com/OriginProtocol/origin/pull/759

**Comment by joshfraser** [comment]
For Facebook, it wasn't about privacy, it was that Facebook disabled the API we needed to get a username.

**Comment by sparrowDom** [comment]
I thought it was about privacy because we could do Facebook attestation the Airbnb way, where users would need to post something on Facebook and we would verify it by fetching that post.

**Comment by joshfraser** [comment]
That's what I'd proposed, but I couldn't convince @matthewliu to get on board. I personally love publicly auditable proofs but Matt thinks they're too confusing for users. Our compromise was to leave things as is for now. We'll revisit once we have a more defined framework around how we're handling identity overall.

**Comment by sparrowDom** [comment]
Sounds good, let deal with this then
