### ISSUE TITLE
Recommended specs for deploying bridge server

### ISSUE THREAD

**Issue by ambertch** [OriginProtocol/origin-bridge#31]
For 3rd party deployments of the bridge server, it would be good to publish guidelines for instance specs, IE recommended instance type for deployment on GCP/Azure/EC2, resource allocation for container / bare metal deployments.

**Comment by joshfraser** [comment]
We're planning to offer the one-click Heroku button for deployments. Obviously this won't scale long-term, but for now, we want to keep the setup that simple where everything will run on a single server without much fuss.

**Comment by tomlinton** [comment]
Closing this as no longer relevant, the bridge server now only handles attestations which should run on just about any specs.
