### ISSUE TITLE
Verify events are generated by legit contracts

### ISSUE THREAD

**Issue by Gzing** [OriginProtocol/origin-bridge#44]
Currently we are grepping events which are basically keccack-256 hashes of the event signatures which can collide with event names from different contracts on the blockchain.
Possible solutions are:
1. Checking bytecode of the event contract and verifying it with the bytecode of origin contracts and it if matches, then we are good and we don't care who deployed the contract since the code is unaltered. Suggested by @DanielVF 
2. Keeping a registry of deployed contracts by origin and checking the emitter address in the events

**Comment by franckc** [comment]
Implemented in EVentListener. Closing.
