### ISSUE TITLE
Design and stub out notifications service

### ISSUE THREAD

**Issue by matthewliu** [OriginProtocol/origin-bridge#6]
Come up with high-level notifications requests and responses.

We'll probably want to support both email and phone number (text) notifications.

There needs to be a way to subscribe to notifications. There also needs to be a way to initiate notification sends to recipients.

**Comment by micahalcorn** [comment]
For example, some likely notifications result from transaction stages:

- Someone has purchased your listing
- Someone has shipped/fulfilled your purchase
- Someone has received your shipment
- Someone has left a review
- Someone has withdrawn your funds (transaction complete)

There may be some notifications from the DApp developer, which may or may not apply to a listing:

- Your listing is about to expire
- Your listing is incomplete
- Your identity contains unpublished attestations
- Something that you follow has changed
- Some listing that you follow is about to sell out
- You have a new message from a counterparty
- You only have a certain time remaining to leave a review
- Your dispute has been received/challenged/approved/etc

I doubt that blockchain confirmations will be tied to these notifications, but if they end up being particularly slow, it might be nice to close the DApp and receive a notification when my blockchain transaction is confirmed.

**Comment by ambertch** [comment]
Hospitality service (Airbnb) notifications:

**Traveler**
- booking request sent
- booking request declined ("Eleanor is unable to host your stay")
- booking request confirmed ("Reservation confirmed")
- request to leave review (for host)
- notification of review (from host)
- message notification

**Host**
- [guess] booking request
- [guess] booking request canceled
- [guess] booking request modified
- request to leave review (for traveler)
- notification of review (from traveler)
- message notification

**Comment by micahalcorn** [comment]
I am going to consider this done since we have a prototype working on bridge/mobile and a non-bridge implementation in js/dapp.
