### ISSUE TITLE
Webhooks

### ISSUE THREAD

**Issue by ambertch** [OriginProtocol/origin-bridge#79]
Developers may want to be notified of events that are related to their DApp or service in order to send notifications or operate on that data (email to leave a review, logic when one of their users creates a listing, etc).

**Comment by franckc** [comment]
Yes, agreed HTTP callbacks would be useful for merchants - it would be a simple way for them to integrate their legacy back-end systems with the Origin platform.
Purely as an example, here are the webhooks PayPal provides to its merchants: https://developer.paypal.com/docs/integration/direct/webhooks/

**Comment by ambertch** [comment]
Examples from ecommerce platform Shopify: https://help.shopify.com/api/reference/events/webhook

**Comment by tomlinton** [comment]
Closed as the event listener has webhook support.
