### ISSUE TITLE
AirBnB verification codes can look like phone numbers

### ISSUE THREAD

**Issue by tyleryasaka** [OriginProtocol/origin-bridge#96]
When testing, I got this verification code: `0x3b06524d`.

AirBnB wasn't too crazy about it.

<img width="245" alt="screen shot 2018-06-25 at 1 43 27 pm" src="https://user-images.githubusercontent.com/6504519/41875538-fb157c18-787f-11e8-9fbd-30b6fb5e36f0.png">

If possible, we should change the format of our codes so that they will never resemble phone numbers.

**Comment by sparrowDom** [comment]
Good idea, tnx.

**Comment by sparrowDom** [comment]
Verification string now consists of 7 words, as discussed in this thread. How it looks: 
<img width="524" alt="screenshot 2018-06-26 15 39 31" src="https://user-images.githubusercontent.com/579910/41917828-6b4e024e-795b-11e8-97c8-9da512d87afb.png">

The fixes have been pushed to [origin-bridge airbnb attestation fix branch](https://github.com/OriginProtocol/origin-bridge/pull/97) and also 1 extra commit has been added to [origin-dapp airbnb attestation branch](https://github.com/OriginProtocol/origin-dapp/pull/278) for UI to account for longer verification codes.

**Comment by micahalcorn** [comment]
Done via #97 ✅
